### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ivanaposdev** [jtransit/route-planner#19]
- [ ] Google Maps / MapBox integration
- [ ] Reverse geocoding search
- [ ] MUI Theming
- [ ] Spring Animations
- [ ] Local storage/session storage custom hook services
- [ ] Firebase integration
