### ISSUE TITLE
Project Initiation

### ISSUE THREAD

**Issue by ivanrodgerapos** [jtransit/route-planner#4]
## TODO 
- [x] #5 
  - [x] Gather requirements 
  - [x] Define objectives
  - [x] Define scope and minimum requirements
  - [x] ~~Define timeline and milestones~~
- [x] #6  
  - [x] Define technologies to be used
  - [x] Create initial architecture 
 - [x] Create deployment plan
